#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ABCLogisticsCloudDatabaseApp
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="FFM")]
	public partial class FFMCloudDataClassesDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertFFM_Accessorial(FFM_Accessorial instance);
    partial void UpdateFFM_Accessorial(FFM_Accessorial instance);
    partial void DeleteFFM_Accessorial(FFM_Accessorial instance);
    partial void InsertFFM_Provider(FFM_Provider instance);
    partial void UpdateFFM_Provider(FFM_Provider instance);
    partial void DeleteFFM_Provider(FFM_Provider instance);
    #endregion
		
		public FFMCloudDataClassesDataContext() : 
				base(global::ABCLogisticsCloudDatabaseApp.Properties.Settings.Default.FFMConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public FFMCloudDataClassesDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public FFMCloudDataClassesDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public FFMCloudDataClassesDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public FFMCloudDataClassesDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<LAXProvider> LAXProviders
		{
			get
			{
				return this.GetTable<LAXProvider>();
			}
		}
		
		public System.Data.Linq.Table<FFM_Accessorial> FFM_Accessorials
		{
			get
			{
				return this.GetTable<FFM_Accessorial>();
			}
		}
		
		public System.Data.Linq.Table<FFM_Provider> FFM_Providers
		{
			get
			{
				return this.GetTable<FFM_Provider>();
			}
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_FFM_InsertProviderDetails")]
		public ISingleResult<SP_FFM_InsertProviderDetailsResult> SP_FFM_InsertProviderDetails(
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="AccountID", DbType="Int")] System.Nullable<int> accountID, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="AccountNo", DbType="NVarChar(100)")] string accountNo, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Name", DbType="NVarChar(100)")] string name, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Address1", DbType="NVarChar(100)")] string address1, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Address2", DbType="NVarChar(100)")] string address2, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Address3", DbType="NVarChar(100)")] string address3, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="City", DbType="NVarChar(50)")] string city, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="State", DbType="NVarChar(50)")] string state, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Postal", DbType="NVarChar(15)")] string postal, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Country", DbType="NVarChar(50)")] string country, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Telephone", DbType="NVarChar(50)")] string telephone, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="PhoneExt", DbType="NVarChar(20)")] string phoneExt, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Fax", DbType="NVarChar(50)")] string fax, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="TollFree", DbType="NVarChar(50)")] string tollFree, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Email", DbType="NVarChar(100)")] string email, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="SortName", DbType="NVarChar(100)")] string sortName, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="SortAddress", DbType="NVarChar(200)")] string sortAddress, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Active", DbType="Bit")] System.Nullable<bool> active, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="TimeZone", DbType="VarChar(50)")] string timeZone, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="BHS", DbType="NVarChar(50)")] string bHS, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="BHE", DbType="NVarChar(50)")] string bHE, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Flag", DbType="Char(1)")] System.Nullable<char> flag, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="ProviderID", DbType="Int")] System.Nullable<int> providerID, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="BTypeId", DbType="Int")] System.Nullable<int> bTypeId, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Bit")] System.Nullable<bool> bRateSigned, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Bit")] System.Nullable<bool> bPrimary, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Bit")] System.Nullable<bool> bEmail, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Bit")] System.Nullable<bool> bFax, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> userId)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), accountID, accountNo, name, address1, address2, address3, city, state, postal, country, telephone, phoneExt, fax, tollFree, email, sortName, sortAddress, active, timeZone, bHS, bHE, flag, providerID, bTypeId, bRateSigned, bPrimary, bEmail, bFax, userId);
			return ((ISingleResult<SP_FFM_InsertProviderDetailsResult>)(result.ReturnValue));
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.LAXProviders")]
	public partial class LAXProvider
	{
		
		private int _ID;
		
		private string _Account_Number;
		
		private string _Name;
		
		private string _Addr1;
		
		private string _Addr2;
		
		private string _Addr3;
		
		private string _City;
		
		private string _State;
		
		private System.Nullable<double> _Zip;
		
		private string _Country;
		
		private string _Phone;
		
		private string _Fax;
		
		private string _Ext;
		
		private string _Toll_Free;
		
		private string _Email;
		
		private string _Time_Zone;
		
		private string _Rate_Signed;
		
		private string _Primary;
		
		public LAXProvider()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.Always, DbType="Int NOT NULL IDENTITY", IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this._ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Account Number]", Storage="_Account_Number", DbType="NVarChar(255)")]
		public string Account_Number
		{
			get
			{
				return this._Account_Number;
			}
			set
			{
				if ((this._Account_Number != value))
				{
					this._Account_Number = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="NVarChar(255)")]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this._Name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Addr1", DbType="NVarChar(255)")]
		public string Addr1
		{
			get
			{
				return this._Addr1;
			}
			set
			{
				if ((this._Addr1 != value))
				{
					this._Addr1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Addr2", DbType="NVarChar(255)")]
		public string Addr2
		{
			get
			{
				return this._Addr2;
			}
			set
			{
				if ((this._Addr2 != value))
				{
					this._Addr2 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Addr3", DbType="NVarChar(255)")]
		public string Addr3
		{
			get
			{
				return this._Addr3;
			}
			set
			{
				if ((this._Addr3 != value))
				{
					this._Addr3 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_City", DbType="NVarChar(255)")]
		public string City
		{
			get
			{
				return this._City;
			}
			set
			{
				if ((this._City != value))
				{
					this._City = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_State", DbType="NVarChar(255)")]
		public string State
		{
			get
			{
				return this._State;
			}
			set
			{
				if ((this._State != value))
				{
					this._State = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Zip", DbType="Float")]
		public System.Nullable<double> Zip
		{
			get
			{
				return this._Zip;
			}
			set
			{
				if ((this._Zip != value))
				{
					this._Zip = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Country", DbType="NVarChar(255)")]
		public string Country
		{
			get
			{
				return this._Country;
			}
			set
			{
				if ((this._Country != value))
				{
					this._Country = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Phone", DbType="NVarChar(255)")]
		public string Phone
		{
			get
			{
				return this._Phone;
			}
			set
			{
				if ((this._Phone != value))
				{
					this._Phone = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fax", DbType="NVarChar(255)")]
		public string Fax
		{
			get
			{
				return this._Fax;
			}
			set
			{
				if ((this._Fax != value))
				{
					this._Fax = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ext", DbType="NVarChar(255)")]
		public string Ext
		{
			get
			{
				return this._Ext;
			}
			set
			{
				if ((this._Ext != value))
				{
					this._Ext = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Toll Free]", Storage="_Toll_Free", DbType="NVarChar(255)")]
		public string Toll_Free
		{
			get
			{
				return this._Toll_Free;
			}
			set
			{
				if ((this._Toll_Free != value))
				{
					this._Toll_Free = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="NVarChar(255)")]
		public string Email
		{
			get
			{
				return this._Email;
			}
			set
			{
				if ((this._Email != value))
				{
					this._Email = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Time Zone]", Storage="_Time_Zone", DbType="NVarChar(255)")]
		public string Time_Zone
		{
			get
			{
				return this._Time_Zone;
			}
			set
			{
				if ((this._Time_Zone != value))
				{
					this._Time_Zone = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Rate Signed]", Storage="_Rate_Signed", DbType="NVarChar(255)")]
		public string Rate_Signed
		{
			get
			{
				return this._Rate_Signed;
			}
			set
			{
				if ((this._Rate_Signed != value))
				{
					this._Rate_Signed = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Primary]", Storage="_Primary", DbType="NVarChar(255)")]
		public string Primary
		{
			get
			{
				return this._Primary;
			}
			set
			{
				if ((this._Primary != value))
				{
					this._Primary = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.FFM_Accessorials")]
	public partial class FFM_Accessorial : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _Accessorial_ID;
		
		private int _ProviderID;
		
		private string _Description;
		
		private System.Nullable<double> _Min_Flat;
		
		private System.Nullable<double> _Rate;
		
		private System.Nullable<int> _ChargeType_Id;
		
		private System.Nullable<System.DateTime> _Hours_Start;
		
		private System.Nullable<System.DateTime> _Hours_End;
		
		private string _Notes;
		
		private System.Nullable<int> _AccDesc_Id;
		
		private System.Nullable<int> _Inclusion;
		
		private System.Nullable<double> _Incremental_Rate;
		
		private System.Nullable<int> _Increment_Range;
		
		private string _CustomerNo;
		
		private EntityRef<FFM_Provider> _FFM_Provider;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnAccessorial_IDChanging(long value);
    partial void OnAccessorial_IDChanged();
    partial void OnProviderIDChanging(int value);
    partial void OnProviderIDChanged();
    partial void OnDescriptionChanging(string value);
    partial void OnDescriptionChanged();
    partial void OnMin_FlatChanging(System.Nullable<double> value);
    partial void OnMin_FlatChanged();
    partial void OnRateChanging(System.Nullable<double> value);
    partial void OnRateChanged();
    partial void OnChargeType_IdChanging(System.Nullable<int> value);
    partial void OnChargeType_IdChanged();
    partial void OnHours_StartChanging(System.Nullable<System.DateTime> value);
    partial void OnHours_StartChanged();
    partial void OnHours_EndChanging(System.Nullable<System.DateTime> value);
    partial void OnHours_EndChanged();
    partial void OnNotesChanging(string value);
    partial void OnNotesChanged();
    partial void OnAccDesc_IdChanging(System.Nullable<int> value);
    partial void OnAccDesc_IdChanged();
    partial void OnInclusionChanging(System.Nullable<int> value);
    partial void OnInclusionChanged();
    partial void OnIncremental_RateChanging(System.Nullable<double> value);
    partial void OnIncremental_RateChanged();
    partial void OnIncrement_RangeChanging(System.Nullable<int> value);
    partial void OnIncrement_RangeChanged();
    partial void OnCustomerNoChanging(string value);
    partial void OnCustomerNoChanged();
    #endregion
		
		public FFM_Accessorial()
		{
			this._FFM_Provider = default(EntityRef<FFM_Provider>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Accessorial_ID", AutoSync=AutoSync.OnInsert, DbType="BigInt NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public long Accessorial_ID
		{
			get
			{
				return this._Accessorial_ID;
			}
			set
			{
				if ((this._Accessorial_ID != value))
				{
					this.OnAccessorial_IDChanging(value);
					this.SendPropertyChanging();
					this._Accessorial_ID = value;
					this.SendPropertyChanged("Accessorial_ID");
					this.OnAccessorial_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProviderID", DbType="Int NOT NULL")]
		public int ProviderID
		{
			get
			{
				return this._ProviderID;
			}
			set
			{
				if ((this._ProviderID != value))
				{
					if (this._FFM_Provider.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnProviderIDChanging(value);
					this.SendPropertyChanging();
					this._ProviderID = value;
					this.SendPropertyChanged("ProviderID");
					this.OnProviderIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Description", DbType="VarChar(150) NOT NULL", CanBeNull=false)]
		public string Description
		{
			get
			{
				return this._Description;
			}
			set
			{
				if ((this._Description != value))
				{
					this.OnDescriptionChanging(value);
					this.SendPropertyChanging();
					this._Description = value;
					this.SendPropertyChanged("Description");
					this.OnDescriptionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Min_Flat", DbType="Float")]
		public System.Nullable<double> Min_Flat
		{
			get
			{
				return this._Min_Flat;
			}
			set
			{
				if ((this._Min_Flat != value))
				{
					this.OnMin_FlatChanging(value);
					this.SendPropertyChanging();
					this._Min_Flat = value;
					this.SendPropertyChanged("Min_Flat");
					this.OnMin_FlatChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Rate", DbType="Float")]
		public System.Nullable<double> Rate
		{
			get
			{
				return this._Rate;
			}
			set
			{
				if ((this._Rate != value))
				{
					this.OnRateChanging(value);
					this.SendPropertyChanging();
					this._Rate = value;
					this.SendPropertyChanged("Rate");
					this.OnRateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ChargeType_Id", DbType="Int")]
		public System.Nullable<int> ChargeType_Id
		{
			get
			{
				return this._ChargeType_Id;
			}
			set
			{
				if ((this._ChargeType_Id != value))
				{
					this.OnChargeType_IdChanging(value);
					this.SendPropertyChanging();
					this._ChargeType_Id = value;
					this.SendPropertyChanged("ChargeType_Id");
					this.OnChargeType_IdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Hours_Start", DbType="DateTime")]
		public System.Nullable<System.DateTime> Hours_Start
		{
			get
			{
				return this._Hours_Start;
			}
			set
			{
				if ((this._Hours_Start != value))
				{
					this.OnHours_StartChanging(value);
					this.SendPropertyChanging();
					this._Hours_Start = value;
					this.SendPropertyChanged("Hours_Start");
					this.OnHours_StartChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Hours_End", DbType="DateTime")]
		public System.Nullable<System.DateTime> Hours_End
		{
			get
			{
				return this._Hours_End;
			}
			set
			{
				if ((this._Hours_End != value))
				{
					this.OnHours_EndChanging(value);
					this.SendPropertyChanging();
					this._Hours_End = value;
					this.SendPropertyChanged("Hours_End");
					this.OnHours_EndChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Notes", DbType="VarChar(300)")]
		public string Notes
		{
			get
			{
				return this._Notes;
			}
			set
			{
				if ((this._Notes != value))
				{
					this.OnNotesChanging(value);
					this.SendPropertyChanging();
					this._Notes = value;
					this.SendPropertyChanged("Notes");
					this.OnNotesChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AccDesc_Id", DbType="Int")]
		public System.Nullable<int> AccDesc_Id
		{
			get
			{
				return this._AccDesc_Id;
			}
			set
			{
				if ((this._AccDesc_Id != value))
				{
					this.OnAccDesc_IdChanging(value);
					this.SendPropertyChanging();
					this._AccDesc_Id = value;
					this.SendPropertyChanged("AccDesc_Id");
					this.OnAccDesc_IdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Inclusion", DbType="Int")]
		public System.Nullable<int> Inclusion
		{
			get
			{
				return this._Inclusion;
			}
			set
			{
				if ((this._Inclusion != value))
				{
					this.OnInclusionChanging(value);
					this.SendPropertyChanging();
					this._Inclusion = value;
					this.SendPropertyChanged("Inclusion");
					this.OnInclusionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Incremental_Rate", DbType="Float")]
		public System.Nullable<double> Incremental_Rate
		{
			get
			{
				return this._Incremental_Rate;
			}
			set
			{
				if ((this._Incremental_Rate != value))
				{
					this.OnIncremental_RateChanging(value);
					this.SendPropertyChanging();
					this._Incremental_Rate = value;
					this.SendPropertyChanged("Incremental_Rate");
					this.OnIncremental_RateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Increment_Range", DbType="Int")]
		public System.Nullable<int> Increment_Range
		{
			get
			{
				return this._Increment_Range;
			}
			set
			{
				if ((this._Increment_Range != value))
				{
					this.OnIncrement_RangeChanging(value);
					this.SendPropertyChanging();
					this._Increment_Range = value;
					this.SendPropertyChanged("Increment_Range");
					this.OnIncrement_RangeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CustomerNo", DbType="NVarChar(20)")]
		public string CustomerNo
		{
			get
			{
				return this._CustomerNo;
			}
			set
			{
				if ((this._CustomerNo != value))
				{
					this.OnCustomerNoChanging(value);
					this.SendPropertyChanging();
					this._CustomerNo = value;
					this.SendPropertyChanged("CustomerNo");
					this.OnCustomerNoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="FFM_Provider_FFM_Accessorial", Storage="_FFM_Provider", ThisKey="ProviderID", OtherKey="ProviderID", IsForeignKey=true)]
		public FFM_Provider FFM_Provider
		{
			get
			{
				return this._FFM_Provider.Entity;
			}
			set
			{
				FFM_Provider previousValue = this._FFM_Provider.Entity;
				if (((previousValue != value) 
							|| (this._FFM_Provider.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._FFM_Provider.Entity = null;
						previousValue.FFM_Accessorials.Remove(this);
					}
					this._FFM_Provider.Entity = value;
					if ((value != null))
					{
						value.FFM_Accessorials.Add(this);
						this._ProviderID = value.ProviderID;
					}
					else
					{
						this._ProviderID = default(int);
					}
					this.SendPropertyChanged("FFM_Provider");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.FFM_Providers")]
	public partial class FFM_Provider : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ProviderID;
		
		private System.Nullable<int> _AccountID;
		
		private System.Nullable<int> _TimeZone;
		
		private string _Business_Hrs_Start;
		
		private string _Business_Hrs_End;
		
		private System.Nullable<bool> _Rates_Signed;
		
		private System.Nullable<bool> _PrimaryFlag;
		
		private System.Nullable<int> _BusinessTypeID;
		
		private System.Nullable<bool> _Email;
		
		private System.Nullable<bool> _Fax;
		
		private string _AccountNumber;
		
		private string _Terminal;
		
		private System.Nullable<bool> _Active;
		
		private string _MasterTerminal;
		
		private System.Nullable<double> _Latitude;
		
		private System.Nullable<double> _Longitude;
		
		private EntitySet<FFM_Accessorial> _FFM_Accessorials;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnProviderIDChanging(int value);
    partial void OnProviderIDChanged();
    partial void OnAccountIDChanging(System.Nullable<int> value);
    partial void OnAccountIDChanged();
    partial void OnTimeZoneChanging(System.Nullable<int> value);
    partial void OnTimeZoneChanged();
    partial void OnBusiness_Hrs_StartChanging(string value);
    partial void OnBusiness_Hrs_StartChanged();
    partial void OnBusiness_Hrs_EndChanging(string value);
    partial void OnBusiness_Hrs_EndChanged();
    partial void OnRates_SignedChanging(System.Nullable<bool> value);
    partial void OnRates_SignedChanged();
    partial void OnPrimaryFlagChanging(System.Nullable<bool> value);
    partial void OnPrimaryFlagChanged();
    partial void OnBusinessTypeIDChanging(System.Nullable<int> value);
    partial void OnBusinessTypeIDChanged();
    partial void OnEmailChanging(System.Nullable<bool> value);
    partial void OnEmailChanged();
    partial void OnFaxChanging(System.Nullable<bool> value);
    partial void OnFaxChanged();
    partial void OnAccountNumberChanging(string value);
    partial void OnAccountNumberChanged();
    partial void OnTerminalChanging(string value);
    partial void OnTerminalChanged();
    partial void OnActiveChanging(System.Nullable<bool> value);
    partial void OnActiveChanged();
    partial void OnMasterTerminalChanging(string value);
    partial void OnMasterTerminalChanged();
    partial void OnLatitudeChanging(System.Nullable<double> value);
    partial void OnLatitudeChanged();
    partial void OnLongitudeChanging(System.Nullable<double> value);
    partial void OnLongitudeChanged();
    #endregion
		
		public FFM_Provider()
		{
			this._FFM_Accessorials = new EntitySet<FFM_Accessorial>(new Action<FFM_Accessorial>(this.attach_FFM_Accessorials), new Action<FFM_Accessorial>(this.detach_FFM_Accessorials));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProviderID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ProviderID
		{
			get
			{
				return this._ProviderID;
			}
			set
			{
				if ((this._ProviderID != value))
				{
					this.OnProviderIDChanging(value);
					this.SendPropertyChanging();
					this._ProviderID = value;
					this.SendPropertyChanged("ProviderID");
					this.OnProviderIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AccountID", DbType="Int")]
		public System.Nullable<int> AccountID
		{
			get
			{
				return this._AccountID;
			}
			set
			{
				if ((this._AccountID != value))
				{
					this.OnAccountIDChanging(value);
					this.SendPropertyChanging();
					this._AccountID = value;
					this.SendPropertyChanged("AccountID");
					this.OnAccountIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TimeZone", DbType="Int")]
		public System.Nullable<int> TimeZone
		{
			get
			{
				return this._TimeZone;
			}
			set
			{
				if ((this._TimeZone != value))
				{
					this.OnTimeZoneChanging(value);
					this.SendPropertyChanging();
					this._TimeZone = value;
					this.SendPropertyChanged("TimeZone");
					this.OnTimeZoneChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Business_Hrs_Start", DbType="VarChar(50)")]
		public string Business_Hrs_Start
		{
			get
			{
				return this._Business_Hrs_Start;
			}
			set
			{
				if ((this._Business_Hrs_Start != value))
				{
					this.OnBusiness_Hrs_StartChanging(value);
					this.SendPropertyChanging();
					this._Business_Hrs_Start = value;
					this.SendPropertyChanged("Business_Hrs_Start");
					this.OnBusiness_Hrs_StartChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Business_Hrs_End", DbType="VarChar(50)")]
		public string Business_Hrs_End
		{
			get
			{
				return this._Business_Hrs_End;
			}
			set
			{
				if ((this._Business_Hrs_End != value))
				{
					this.OnBusiness_Hrs_EndChanging(value);
					this.SendPropertyChanging();
					this._Business_Hrs_End = value;
					this.SendPropertyChanged("Business_Hrs_End");
					this.OnBusiness_Hrs_EndChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Rates_Signed", DbType="Bit")]
		public System.Nullable<bool> Rates_Signed
		{
			get
			{
				return this._Rates_Signed;
			}
			set
			{
				if ((this._Rates_Signed != value))
				{
					this.OnRates_SignedChanging(value);
					this.SendPropertyChanging();
					this._Rates_Signed = value;
					this.SendPropertyChanged("Rates_Signed");
					this.OnRates_SignedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PrimaryFlag", DbType="Bit")]
		public System.Nullable<bool> PrimaryFlag
		{
			get
			{
				return this._PrimaryFlag;
			}
			set
			{
				if ((this._PrimaryFlag != value))
				{
					this.OnPrimaryFlagChanging(value);
					this.SendPropertyChanging();
					this._PrimaryFlag = value;
					this.SendPropertyChanged("PrimaryFlag");
					this.OnPrimaryFlagChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BusinessTypeID", DbType="Int")]
		public System.Nullable<int> BusinessTypeID
		{
			get
			{
				return this._BusinessTypeID;
			}
			set
			{
				if ((this._BusinessTypeID != value))
				{
					this.OnBusinessTypeIDChanging(value);
					this.SendPropertyChanging();
					this._BusinessTypeID = value;
					this.SendPropertyChanged("BusinessTypeID");
					this.OnBusinessTypeIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="Bit")]
		public System.Nullable<bool> Email
		{
			get
			{
				return this._Email;
			}
			set
			{
				if ((this._Email != value))
				{
					this.OnEmailChanging(value);
					this.SendPropertyChanging();
					this._Email = value;
					this.SendPropertyChanged("Email");
					this.OnEmailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fax", DbType="Bit")]
		public System.Nullable<bool> Fax
		{
			get
			{
				return this._Fax;
			}
			set
			{
				if ((this._Fax != value))
				{
					this.OnFaxChanging(value);
					this.SendPropertyChanging();
					this._Fax = value;
					this.SendPropertyChanged("Fax");
					this.OnFaxChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AccountNumber", DbType="VarChar(50)")]
		public string AccountNumber
		{
			get
			{
				return this._AccountNumber;
			}
			set
			{
				if ((this._AccountNumber != value))
				{
					this.OnAccountNumberChanging(value);
					this.SendPropertyChanging();
					this._AccountNumber = value;
					this.SendPropertyChanged("AccountNumber");
					this.OnAccountNumberChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Terminal", DbType="VarChar(10)")]
		public string Terminal
		{
			get
			{
				return this._Terminal;
			}
			set
			{
				if ((this._Terminal != value))
				{
					this.OnTerminalChanging(value);
					this.SendPropertyChanging();
					this._Terminal = value;
					this.SendPropertyChanged("Terminal");
					this.OnTerminalChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Active", DbType="Bit")]
		public System.Nullable<bool> Active
		{
			get
			{
				return this._Active;
			}
			set
			{
				if ((this._Active != value))
				{
					this.OnActiveChanging(value);
					this.SendPropertyChanging();
					this._Active = value;
					this.SendPropertyChanged("Active");
					this.OnActiveChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MasterTerminal", DbType="VarChar(3)")]
		public string MasterTerminal
		{
			get
			{
				return this._MasterTerminal;
			}
			set
			{
				if ((this._MasterTerminal != value))
				{
					this.OnMasterTerminalChanging(value);
					this.SendPropertyChanging();
					this._MasterTerminal = value;
					this.SendPropertyChanged("MasterTerminal");
					this.OnMasterTerminalChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Latitude", DbType="Float")]
		public System.Nullable<double> Latitude
		{
			get
			{
				return this._Latitude;
			}
			set
			{
				if ((this._Latitude != value))
				{
					this.OnLatitudeChanging(value);
					this.SendPropertyChanging();
					this._Latitude = value;
					this.SendPropertyChanged("Latitude");
					this.OnLatitudeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Longitude", DbType="Float")]
		public System.Nullable<double> Longitude
		{
			get
			{
				return this._Longitude;
			}
			set
			{
				if ((this._Longitude != value))
				{
					this.OnLongitudeChanging(value);
					this.SendPropertyChanging();
					this._Longitude = value;
					this.SendPropertyChanged("Longitude");
					this.OnLongitudeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="FFM_Provider_FFM_Accessorial", Storage="_FFM_Accessorials", ThisKey="ProviderID", OtherKey="ProviderID")]
		public EntitySet<FFM_Accessorial> FFM_Accessorials
		{
			get
			{
				return this._FFM_Accessorials;
			}
			set
			{
				this._FFM_Accessorials.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_FFM_Accessorials(FFM_Accessorial entity)
		{
			this.SendPropertyChanging();
			entity.FFM_Provider = this;
		}
		
		private void detach_FFM_Accessorials(FFM_Accessorial entity)
		{
			this.SendPropertyChanging();
			entity.FFM_Provider = null;
		}
	}
	
	public partial class SP_FFM_InsertProviderDetailsResult
	{
		
		private System.Nullable<int> _Column1;
		
		public SP_FFM_InsertProviderDetailsResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="", Storage="_Column1", DbType="Int")]
		public System.Nullable<int> Column1
		{
			get
			{
				return this._Column1;
			}
			set
			{
				if ((this._Column1 != value))
				{
					this._Column1 = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
