//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.17929.
// 
#pragma warning disable 1591

namespace CarrierIntegrationCore.UPSPickupWebReference {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="PickupBinding", Namespace="http://www.ups.com/WSDL/XOLTWS/Pickup/v1.1")]
    public partial class PickupService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private UPSSecurity uPSSecurityValueField;
        
        private System.Threading.SendOrPostCallback ProcessPickupCreationOperationCompleted;
        
        private System.Threading.SendOrPostCallback ProcessPickupRateOperationCompleted;
        
        private System.Threading.SendOrPostCallback ProcessPickupCancelOperationCompleted;
        
        private System.Threading.SendOrPostCallback ProcessPickupPendingStatusOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public PickupService() {
            this.Url = global::CarrierIntegrationCore.Booking.Properties.Settings.Default.CarrierIntegrationCore.Booking_UPSPickupWebReference_PickupService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public UPSSecurity UPSSecurityValue {
            get {
                return this.uPSSecurityValueField;
            }
            set {
                this.uPSSecurityValueField = value;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event ProcessPickupCreationCompletedEventHandler ProcessPickupCreationCompleted;
        
        /// <remarks/>
        public event ProcessPickupRateCompletedEventHandler ProcessPickupRateCompleted;
        
        /// <remarks/>
        public event ProcessPickupCancelCompletedEventHandler ProcessPickupCancelCompleted;
        
        /// <remarks/>
        public event ProcessPickupPendingStatusCompletedEventHandler ProcessPickupPendingStatusCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("UPSSecurityValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://onlinetools.ups.com/webservices/PickupBinding/v1.1", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("PickupCreationResponse", Namespace="http://www.ups.com/XMLSchema/XOLTWS/Pickup/v1.1")]
        public PickupCreationResponse ProcessPickupCreation([System.Xml.Serialization.XmlElementAttribute(Namespace="http://www.ups.com/XMLSchema/XOLTWS/Pickup/v1.1")] PickupCreationRequest PickupCreationRequest) {
            object[] results = this.Invoke("ProcessPickupCreation", new object[] {
                        PickupCreationRequest});
            return ((PickupCreationResponse)(results[0]));
        }
        
        /// <remarks/>
        public void ProcessPickupCreationAsync(PickupCreationRequest PickupCreationRequest) {
            this.ProcessPickupCreationAsync(PickupCreationRequest, null);
        }
        
        /// <remarks/>
        public void ProcessPickupCreationAsync(PickupCreationRequest PickupCreationRequest, object userState) {
            if ((this.ProcessPickupCreationOperationCompleted == null)) {
                this.ProcessPickupCreationOperationCompleted = new System.Threading.SendOrPostCallback(this.OnProcessPickupCreationOperationCompleted);
            }
            this.InvokeAsync("ProcessPickupCreation", new object[] {
                        PickupCreationRequest}, this.ProcessPickupCreationOperationCompleted, userState);
        }
        
        private void OnProcessPickupCreationOperationCompleted(object arg) {
            if ((this.ProcessPickupCreationCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ProcessPickupCreationCompleted(this, new ProcessPickupCreationCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("UPSSecurityValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://onlinetools.ups.com/webservices/PickupBinding/v1.1", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("PickupRateResponse", Namespace="http://www.ups.com/XMLSchema/XOLTWS/Pickup/v1.1")]
        public PickupRateResponse ProcessPickupRate([System.Xml.Serialization.XmlElementAttribute(Namespace="http://www.ups.com/XMLSchema/XOLTWS/Pickup/v1.1")] PickupRateRequest PickupRateRequest) {
            object[] results = this.Invoke("ProcessPickupRate", new object[] {
                        PickupRateRequest});
            return ((PickupRateResponse)(results[0]));
        }
        
        /// <remarks/>
        public void ProcessPickupRateAsync(PickupRateRequest PickupRateRequest) {
            this.ProcessPickupRateAsync(PickupRateRequest, null);
        }
        
        /// <remarks/>
        public void ProcessPickupRateAsync(PickupRateRequest PickupRateRequest, object userState) {
            if ((this.ProcessPickupRateOperationCompleted == null)) {
                this.ProcessPickupRateOperationCompleted = new System.Threading.SendOrPostCallback(this.OnProcessPickupRateOperationCompleted);
            }
            this.InvokeAsync("ProcessPickupRate", new object[] {
                        PickupRateRequest}, this.ProcessPickupRateOperationCompleted, userState);
        }
        
        private void OnProcessPickupRateOperationCompleted(object arg) {
            if ((this.ProcessPickupRateCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ProcessPickupRateCompleted(this, new ProcessPickupRateCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("UPSSecurityValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://onlinetools.ups.com/webservices/PickupBinding/v1.1", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("PickupCancelResponse", Namespace="http://www.ups.com/XMLSchema/XOLTWS/Pickup/v1.1")]
        public PickupCancelResponse ProcessPickupCancel([System.Xml.Serialization.XmlElementAttribute(Namespace="http://www.ups.com/XMLSchema/XOLTWS/Pickup/v1.1")] PickupCancelRequest PickupCancelRequest) {
            object[] results = this.Invoke("ProcessPickupCancel", new object[] {
                        PickupCancelRequest});
            return ((PickupCancelResponse)(results[0]));
        }
        
        /// <remarks/>
        public void ProcessPickupCancelAsync(PickupCancelRequest PickupCancelRequest) {
            this.ProcessPickupCancelAsync(PickupCancelRequest, null);
        }
        
        /// <remarks/>
        public void ProcessPickupCancelAsync(PickupCancelRequest PickupCancelRequest, object userState) {
            if ((this.ProcessPickupCancelOperationCompleted == null)) {
                this.ProcessPickupCancelOperationCompleted = new System.Threading.SendOrPostCallback(this.OnProcessPickupCancelOperationCompleted);
            }
            this.InvokeAsync("ProcessPickupCancel", new object[] {
                        PickupCancelRequest}, this.ProcessPickupCancelOperationCompleted, userState);
        }
        
        private void OnProcessPickupCancelOperationCompleted(object arg) {
            if ((this.ProcessPickupCancelCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ProcessPickupCancelCompleted(this, new ProcessPickupCancelCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("UPSSecurityValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://onlinetools.ups.com/webservices/PickupBinding/v1.1", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("PickupPendingStatusResponse", Namespace="http://www.ups.com/XMLSchema/XOLTWS/Pickup/v1.1")]
        public PickupPendingStatusResponse ProcessPickupPendingStatus([System.Xml.Serialization.XmlElementAttribute(Namespace="http://www.ups.com/XMLSchema/XOLTWS/Pickup/v1.1")] PickupPendingStatusRequest PickupPendingStatusRequest) {
            object[] results = this.Invoke("ProcessPickupPendingStatus", new object[] {
                        PickupPendingStatusRequest});
            return ((PickupPendingStatusResponse)(results[0]));
        }
        
        /// <remarks/>
        public void ProcessPickupPendingStatusAsync(PickupPendingStatusRequest PickupPendingStatusRequest) {
            this.ProcessPickupPendingStatusAsync(PickupPendingStatusRequest, null);
        }
        
        /// <remarks/>
        public void ProcessPickupPendingStatusAsync(PickupPendingStatusRequest PickupPendingStatusRequest, object userState) {
            if ((this.ProcessPickupPendingStatusOperationCompleted == null)) {
                this.ProcessPickupPendingStatusOperationCompleted = new System.Threading.SendOrPostCallback(this.OnProcessPickupPendingStatusOperationCompleted);
            }
            this.InvokeAsync("ProcessPickupPendingStatus", new object[] {
                        PickupPendingStatusRequest}, this.ProcessPickupPendingStatusOperationCompleted, userState);
        }
        
        private void OnProcessPickupPendingStatusOperationCompleted(object arg) {
            if ((this.ProcessPickupPendingStatusCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ProcessPickupPendingStatusCompleted(this, new ProcessPickupPendingStatusCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.ups.com/XMLSchema/XOLTWS/UPSS/v1.0")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.ups.com/XMLSchema/XOLTWS/UPSS/v1.0", IsNullable=false)]
    public partial class UPSSecurity : System.Web.Services.Protocols.SoapHeader {
        
        private UPSSecurityUsernameToken usernameTokenField;
        
        private UPSSecurityServiceAccessToken serviceAccessTokenField;
        
        /// <remarks/>
        public UPSSecurityUsernameToken UsernameToken {
            get {
                return this.usernameTokenField;
            }
            set {
                this.usernameTokenField = value;
            }
        }
        
        /// <remarks/>
        public UPSSecurityServiceAccessToken ServiceAccessToken {
            get {
                return this.serviceAccessTokenField;
            }
            set {
                this.serviceAccessTokenField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.ups.com/XMLSchema/XOLTWS/UPSS/v1.0")]
    public partial class UPSSecurityUsernameToken {
        
        private string usernameField;
        
        private string passwordField;
        
        /// <remarks/>
        public string Username {
            get {
                return this.usernameField;
            }
            set {
                this.usernameField = value;
            }
        }
        
        /// <remarks/>
        public string Password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ups.com/XMLSchema/XOLTWS/Pickup/v1.1")]
    public partial class PendingStatusType {
        
        private string pickupTypeField;
        
        private string serviceDateField;
        
        private string pRNField;
        
        private string gWNStatusCodeField;
        
        private string onCallStatusCodeField;
        
        private string pickupStatusMessageField;
        
        private string billingCodeField;
        
        private string contactNameField;
        
        private string referenceNumberField;
        
        /// <remarks/>
        public string PickupType {
            get {
                return this.pickupTypeField;
            }
            set {
                this.pickupTypeField = value;
            }
        }
        
        /// <remarks/>
        public string ServiceDate {
            get {
                return this.serviceDateField;
            }
            set {
                this.serviceDateField = value;
            }
        }
        
        /// <remarks/>
        public string PRN {
            get {
                return this.pRNField;
            }
            set {
                this.pRNField = value;
            }
        }
        
        /// <remarks/>
        public string GWNStatusCode {
            get {
                return this.gWNStatusCodeField;
            }
            set {
                this.gWNStatusCodeField = value;
            }
        }
        
        /// <remarks/>
        public string OnCallStatusCode {
            get {
                return this.onCallStatusCodeField;
            }
            set {
                this.onCallStatusCodeField = value;
            }
        }
        
        /// <remarks/>
        public string PickupStatusMessage {
            get {
                return this.pickupStatusMessageField;
            }
            set {
                this.pickupStatusMessageField = value;
            }
        }
        
        /// <remarks/>
        public string BillingCode {
            get {
                return this.billingCodeField;
            }
            set {
                this.billingCodeField = value;
            }
        }
        
        /// <remarks/>
        public string ContactName {
            get {
                return this.contactNameField;
            }
            set {
                this.contactNameField = value;
            }
        }
        
        /// <remarks/>
        public string ReferenceNumber {
            get {
                return this.referenceNumberField;
            }
            set {
                this.referenceNumberField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ups.com/XMLSchema/XOLTWS/Pickup/v1.1")]
    public partial class AddressType {
        
        private string[] addressLineField;
        
        private string cityField;
        
        private string stateProvinceField;
        
        private string postalCodeField;
        
        private string countryCodeField;
        
        private string residentialIndicatorField;
        
        public AddressType() {
            this.residentialIndicatorField = "N";
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("AddressLine")]
        public string[] AddressLine {
            get {
                return this.addressLineField;
            }
            set {
                this.addressLineField = value;
            }
        }
        
        /// <remarks/>
        public string City {
            get {
                return this.cityField;
            }
            set {
                this.cityField = value;
            }
        }
        
        /// <remarks/>
        public string StateProvince {
            get {
                return this.stateProvinceField;
            }
            set {
                this.stateProvinceField = value;
            }
        }
        
        /// <remarks/>
        public string PostalCode {
            get {
                return this.postalCodeField;
            }
            set {
                this.postalCodeField = value;
            }
        }
        
        /// <remarks/>
        public string CountryCode {
            get {
                return this.countryCodeField;
            }
            set {
                this.countryCodeField = value;
            }
        }
        
        /// <remarks/>
        public string ResidentialIndicator {
            get {
                return this.residentialIndicatorField;
            }
            set {
                this.residentialIndicatorField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ups.com/XMLSchema/XOLTWS/Pickup/v1.1")]
    public partial class ChargeDetailType {
        
        private string chargeCodeField;
        
        private string chargeDescriptionField;
        
        private string chargeAmountField;
        
        private string taxAmountField;
        
        /// <remarks/>
        public string ChargeCode {
            get {
                return this.chargeCodeField;
            }
            set {
                this.chargeCodeField = value;
            }
        }
        
        /// <remarks/>
        public string ChargeDescription {
            get {
                return this.chargeDescriptionField;
            }
            set {
                this.chargeDescriptionField = value;
            }
        }
        
        /// <remarks/>
        public string ChargeAmount {
            get {
                return this.chargeAmountField;
            }
            set {
                this.chargeAmountField = value;
            }
        }
        
        /// <remarks/>
        public string TaxAmount {
            get {
                return this.taxAmountField;
            }
            set {
                this.taxAmountField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ups.com/XMLSchema/XOLTWS/Pickup/v1.1")]
    public partial class RateResultType {
        
        private string rateTypeField;
        
        private string currencyCodeField;
        
        private ChargeDetailType[] chargeDetailField;
        
        private string totalTaxField;
        
        private string grandTotalOfAllChargeField;
        
        /// <remarks/>
        public string RateType {
            get {
                return this.rateTypeField;
            }
            set {
                this.rateTypeField = value;
            }
        }
        
        /// <remarks/>
        public string CurrencyCode {
            get {
                return this.currencyCodeField;
            }
            set {
                this.currencyCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ChargeDetail")]
        public ChargeDetailType[] ChargeDetail {
            get {
                return this.chargeDetailField;
            }
            set {
                this.chargeDetailField = value;
            }
        }
        
        /// <remarks/>
        public string TotalTax {
            get {
                return this.totalTaxField;
            }
            set {
                this.totalTaxField = value;
            }
        }
        
        /// <remarks/>
        public string GrandTotalOfAllCharge {
            get {
                return this.grandTotalOfAllChargeField;
            }
            set {
                this.grandTotalOfAllChargeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ups.com/XMLSchema/XOLTWS/Pickup/v1.1")]
    public partial class StatusCodeDescriptionType {
        
        private string codeField;
        
        private string descriptionField;
        
        /// <remarks/>
        public string Code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
            }
        }
        
        /// <remarks/>
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ups.com/XMLSchema/XOLTWS/Common/v1.0")]
    public partial class CodeDescriptionType {
        
        private string codeField;
        
        private string descriptionField;
        
        /// <remarks/>
        public string Code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
            }
        }
        
        /// <remarks/>
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ups.com/XMLSchema/XOLTWS/Common/v1.0")]
    public partial class ResponseType {
        
        private CodeDescriptionType responseStatusField;
        
        private CodeDescriptionType[] alertField;
        
        private TransactionReferenceType transactionReferenceField;
        
        /// <remarks/>
        public CodeDescriptionType ResponseStatus {
            get {
                return this.responseStatusField;
            }
            set {
                this.responseStatusField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Alert")]
        public CodeDescriptionType[] Alert {
            get {
                return this.alertField;
            }
            set {
                this.alertField = value;
            }
        }
        
        /// <remarks/>
        public TransactionReferenceType TransactionReference {
            get {
                return this.transactionReferenceField;
            }
            set {
                this.transactionReferenceField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ups.com/XMLSchema/XOLTWS/Common/v1.0")]
    public partial class TransactionReferenceType {
        
        private string customerContextField;
        
        private string transactionIdentifierField;
        
        /// <remarks/>
        public string CustomerContext {
            get {
                return this.customerContextField;
            }
            set {
                this.customerContextField = value;
            }
        }
        
        /// <remarks/>
        public string TransactionIdentifier {
            get {
                return this.transactionIdentifierField;
            }
            set {
                this.transactionIdentifierField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ups.com/XMLSchema/XOLTWS/Pickup/v1.1")]
    public partial class NotificationType {
        
        private string[] confirmationEmailAddressField;
        
        private string undeliverableEmailAddressField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ConfirmationEmailAddress")]
        public string[] ConfirmationEmailAddress {
            get {
                return this.confirmationEmailAddressField;
            }
            set {
                this.confirmationEmailAddressField = value;
            }
        }
        
        /// <remarks/>
        public string UndeliverableEmailAddress {
            get {
                return this.undeliverableEmailAddressField;
            }
            set {
                this.undeliverableEmailAddressField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ups.com/XMLSchema/XOLTWS/Pickup/v1.1")]
    public partial class WeightType {
        
        private string weightField;
        
        private string unitOfMeasurementField;
        
        /// <remarks/>
        public string Weight {
            get {
                return this.weightField;
            }
            set {
                this.weightField = value;
            }
        }
        
        /// <remarks/>
        public string UnitOfMeasurement {
            get {
                return this.unitOfMeasurementField;
            }
            set {
                this.unitOfMeasurementField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ups.com/XMLSchema/XOLTWS/Pickup/v1.1")]
    public partial class PickupPieceType {
        
        private string serviceCodeField;
        
        private string quantityField;
        
        private string destinationCountryCodeField;
        
        private string containerCodeField;
        
        /// <remarks/>
        public string ServiceCode {
            get {
                return this.serviceCodeField;
            }
            set {
                this.serviceCodeField = value;
            }
        }
        
        /// <remarks/>
        public string Quantity {
            get {
                return this.quantityField;
            }
            set {
                this.quantityField = value;
            }
        }
        
        /// <remarks/>
        public string DestinationCountryCode {
            get {
                return this.destinationCountryCodeField;
            }
            set {
                this.destinationCountryCodeField = value;
            }
        }
        
        /// <remarks/>
        public string ContainerCode {
            get {
                return this.containerCodeField;
            }
            set {
                this.containerCodeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ups.com/XMLSchema/XOLTWS/Pickup/v1.1")]
    public partial class PhoneType {
        
        private string numberField;
        
        private string extensionField;
        
        /// <remarks/>
        public string Number {
            get {
                return this.numberField;
            }
            set {
                this.numberField = value;
            }
        }
        
        /// <remarks/>
        public string Extension {
            get {
                return this.extensionField;
            }
            set {
                this.extensionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ups.com/XMLSchema/XOLTWS/Pickup/v1.1")]
    public partial class PickupAddressType {
        
        private string companyNameField;
        
        private string contactNameField;
        
        private string[] addressLineField;
        
        private string roomField;
        
        private string floorField;
        
        private string cityField;
        
        private string stateProvinceField;
        
        private string urbanizationField;
        
        private string postalCodeField;
        
        private string countryCodeField;
        
        private string residentialIndicatorField;
        
        private string pickupPointField;
        
        private PhoneType phoneField;
        
        public PickupAddressType() {
            this.residentialIndicatorField = "N";
        }
        
        /// <remarks/>
        public string CompanyName {
            get {
                return this.companyNameField;
            }
            set {
                this.companyNameField = value;
            }
        }
        
        /// <remarks/>
        public string ContactName {
            get {
                return this.contactNameField;
            }
            set {
                this.contactNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("AddressLine")]
        public string[] AddressLine {
            get {
                return this.addressLineField;
            }
            set {
                this.addressLineField = value;
            }
        }
        
        /// <remarks/>
        public string Room {
            get {
                return this.roomField;
            }
            set {
                this.roomField = value;
            }
        }
        
        /// <remarks/>
        public string Floor {
            get {
                return this.floorField;
            }
            set {
                this.floorField = value;
            }
        }
        
        /// <remarks/>
        public string City {
            get {
                return this.cityField;
            }
            set {
                this.cityField = value;
            }
        }
        
        /// <remarks/>
        public string StateProvince {
            get {
                return this.stateProvinceField;
            }
            set {
                this.stateProvinceField = value;
            }
        }
        
        /// <remarks/>
        public string Urbanization {
            get {
                return this.urbanizationField;
            }
            set {
                this.urbanizationField = value;
            }
        }
        
        /// <remarks/>
        public string PostalCode {
            get {
                return this.postalCodeField;
            }
            set {
                this.postalCodeField = value;
            }
        }
        
        /// <remarks/>
        public string CountryCode {
            get {
                return this.countryCodeField;
            }
            set {
                this.countryCodeField = value;
            }
        }
        
        /// <remarks/>
        public string ResidentialIndicator {
            get {
                return this.residentialIndicatorField;
            }
            set {
                this.residentialIndicatorField = value;
            }
        }
        
        /// <remarks/>
        public string PickupPoint {
            get {
                return this.pickupPointField;
            }
            set {
                this.pickupPointField = value;
            }
        }
        
        /// <remarks/>
        public PhoneType Phone {
            get {
                return this.phoneField;
            }
            set {
                this.phoneField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ups.com/XMLSchema/XOLTWS/Pickup/v1.1")]
    public partial class PickupDateInfoType {
        
        private string closeTimeField;
        
        private string readyTimeField;
        
        private string pickupDateField;
        
        /// <remarks/>
        public string CloseTime {
            get {
                return this.closeTimeField;
            }
            set {
                this.closeTimeField = value;
            }
        }
        
        /// <remarks/>
        public string ReadyTime {
            get {
                return this.readyTimeField;
            }
            set {
                this.readyTimeField = value;
            }
        }
        
        /// <remarks/>
        public string PickupDate {
            get {
                return this.pickupDateField;
            }
            set {
                this.pickupDateField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ups.com/XMLSchema/XOLTWS/Pickup/v1.1")]
    public partial class ChargeCardAddressType {
        
        private string[] addressLineField;
        
        private string cityField;
        
        private string stateProvinceField;
        
        private string postalCodeField;
        
        private string countryCodeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("AddressLine")]
        public string[] AddressLine {
            get {
                return this.addressLineField;
            }
            set {
                this.addressLineField = value;
            }
        }
        
        /// <remarks/>
        public string City {
            get {
                return this.cityField;
            }
            set {
                this.cityField = value;
            }
        }
        
        /// <remarks/>
        public string StateProvince {
            get {
                return this.stateProvinceField;
            }
            set {
                this.stateProvinceField = value;
            }
        }
        
        /// <remarks/>
        public string PostalCode {
            get {
                return this.postalCodeField;
            }
            set {
                this.postalCodeField = value;
            }
        }
        
        /// <remarks/>
        public string CountryCode {
            get {
                return this.countryCodeField;
            }
            set {
                this.countryCodeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ups.com/XMLSchema/XOLTWS/Pickup/v1.1")]
    public partial class ChargeCardType {
        
        private string cardHolderNameField;
        
        private string cardTypeField;
        
        private string cardNumberField;
        
        private string expirationDateField;
        
        private string securityCodeField;
        
        private ChargeCardAddressType cardAddressField;
        
        /// <remarks/>
        public string CardHolderName {
            get {
                return this.cardHolderNameField;
            }
            set {
                this.cardHolderNameField = value;
            }
        }
        
        /// <remarks/>
        public string CardType {
            get {
                return this.cardTypeField;
            }
            set {
                this.cardTypeField = value;
            }
        }
        
        /// <remarks/>
        public string CardNumber {
            get {
                return this.cardNumberField;
            }
            set {
                this.cardNumberField = value;
            }
        }
        
        /// <remarks/>
        public string ExpirationDate {
            get {
                return this.expirationDateField;
            }
            set {
                this.expirationDateField = value;
            }
        }
        
        /// <remarks/>
        public string SecurityCode {
            get {
                return this.securityCodeField;
            }
            set {
                this.securityCodeField = value;
            }
        }
        
        /// <remarks/>
        public ChargeCardAddressType CardAddress {
            get {
                return this.cardAddressField;
            }
            set {
                this.cardAddressField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ups.com/XMLSchema/XOLTWS/Pickup/v1.1")]
    public partial class AccountType {
        
        private string accountNumberField;
        
        private string accountCountryCodeField;
        
        /// <remarks/>
        public string AccountNumber {
            get {
                return this.accountNumberField;
            }
            set {
                this.accountNumberField = value;
            }
        }
        
        /// <remarks/>
        public string AccountCountryCode {
            get {
                return this.accountCountryCodeField;
            }
            set {
                this.accountCountryCodeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ups.com/XMLSchema/XOLTWS/Pickup/v1.1")]
    public partial class ShipperType {
        
        private AccountType accountField;
        
        private ChargeCardType chargeCardField;
        
        /// <remarks/>
        public AccountType Account {
            get {
                return this.accountField;
            }
            set {
                this.accountField = value;
            }
        }
        
        /// <remarks/>
        public ChargeCardType ChargeCard {
            get {
                return this.chargeCardField;
            }
            set {
                this.chargeCardField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ups.com/XMLSchema/XOLTWS/Common/v1.0")]
    public partial class RequestType {
        
        private string[] requestOptionField;
        
        private TransactionReferenceType transactionReferenceField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("RequestOption")]
        public string[] RequestOption {
            get {
                return this.requestOptionField;
            }
            set {
                this.requestOptionField = value;
            }
        }
        
        /// <remarks/>
        public TransactionReferenceType TransactionReference {
            get {
                return this.transactionReferenceField;
            }
            set {
                this.transactionReferenceField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.ups.com/XMLSchema/XOLTWS/UPSS/v1.0")]
    public partial class UPSSecurityServiceAccessToken {
        
        private string accessLicenseNumberField;
        
        /// <remarks/>
        public string AccessLicenseNumber {
            get {
                return this.accessLicenseNumberField;
            }
            set {
                this.accessLicenseNumberField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.ups.com/XMLSchema/XOLTWS/Pickup/v1.1")]
    public partial class PickupCreationRequest {
        
        private RequestType requestField;
        
        private string ratePickupIndicatorField;
        
        private ShipperType shipperField;
        
        private PickupDateInfoType pickupDateInfoField;
        
        private PickupAddressType pickupAddressField;
        
        private string alternateAddressIndicatorField;
        
        private PickupPieceType[] pickupPieceField;
        
        private WeightType totalWeightField;
        
        private string overweightIndicatorField;
        
        private string[] returnTrackingNumberField;
        
        private string paymentMethodField;
        
        private string specialInstructionField;
        
        private string referenceNumberField;
        
        private NotificationType notificationField;
        
        public PickupCreationRequest() {
            this.ratePickupIndicatorField = "N";
            this.alternateAddressIndicatorField = "N";
            this.overweightIndicatorField = "N";
            this.paymentMethodField = "00";
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://www.ups.com/XMLSchema/XOLTWS/Common/v1.0")]
        public RequestType Request {
            get {
                return this.requestField;
            }
            set {
                this.requestField = value;
            }
        }
        
        /// <remarks/>
        public string RatePickupIndicator {
            get {
                return this.ratePickupIndicatorField;
            }
            set {
                this.ratePickupIndicatorField = value;
            }
        }
        
        /// <remarks/>
        public ShipperType Shipper {
            get {
                return this.shipperField;
            }
            set {
                this.shipperField = value;
            }
        }
        
        /// <remarks/>
        public PickupDateInfoType PickupDateInfo {
            get {
                return this.pickupDateInfoField;
            }
            set {
                this.pickupDateInfoField = value;
            }
        }
        
        /// <remarks/>
        public PickupAddressType PickupAddress {
            get {
                return this.pickupAddressField;
            }
            set {
                this.pickupAddressField = value;
            }
        }
        
        /// <remarks/>
        public string AlternateAddressIndicator {
            get {
                return this.alternateAddressIndicatorField;
            }
            set {
                this.alternateAddressIndicatorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("PickupPiece")]
        public PickupPieceType[] PickupPiece {
            get {
                return this.pickupPieceField;
            }
            set {
                this.pickupPieceField = value;
            }
        }
        
        /// <remarks/>
        public WeightType TotalWeight {
            get {
                return this.totalWeightField;
            }
            set {
                this.totalWeightField = value;
            }
        }
        
        /// <remarks/>
        public string OverweightIndicator {
            get {
                return this.overweightIndicatorField;
            }
            set {
                this.overweightIndicatorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ReturnTrackingNumber")]
        public string[] ReturnTrackingNumber {
            get {
                return this.returnTrackingNumberField;
            }
            set {
                this.returnTrackingNumberField = value;
            }
        }
        
        /// <remarks/>
        public string PaymentMethod {
            get {
                return this.paymentMethodField;
            }
            set {
                this.paymentMethodField = value;
            }
        }
        
        /// <remarks/>
        public string SpecialInstruction {
            get {
                return this.specialInstructionField;
            }
            set {
                this.specialInstructionField = value;
            }
        }
        
        /// <remarks/>
        public string ReferenceNumber {
            get {
                return this.referenceNumberField;
            }
            set {
                this.referenceNumberField = value;
            }
        }
        
        /// <remarks/>
        public NotificationType Notification {
            get {
                return this.notificationField;
            }
            set {
                this.notificationField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.ups.com/XMLSchema/XOLTWS/Pickup/v1.1")]
    public partial class PickupCreationResponse {
        
        private ResponseType responseField;
        
        private string pRNField;
        
        private StatusCodeDescriptionType rateStatusField;
        
        private RateResultType rateResultField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://www.ups.com/XMLSchema/XOLTWS/Common/v1.0")]
        public ResponseType Response {
            get {
                return this.responseField;
            }
            set {
                this.responseField = value;
            }
        }
        
        /// <remarks/>
        public string PRN {
            get {
                return this.pRNField;
            }
            set {
                this.pRNField = value;
            }
        }
        
        /// <remarks/>
        public StatusCodeDescriptionType RateStatus {
            get {
                return this.rateStatusField;
            }
            set {
                this.rateStatusField = value;
            }
        }
        
        /// <remarks/>
        public RateResultType RateResult {
            get {
                return this.rateResultField;
            }
            set {
                this.rateResultField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.ups.com/XMLSchema/XOLTWS/Pickup/v1.1")]
    public partial class PickupRateRequest {
        
        private RequestType requestField;
        
        private AddressType pickupAddressField;
        
        private string alternateAddressIndicatorField;
        
        private string serviceDateOptionField;
        
        private PickupDateInfoType pickupDateInfoField;
        
        public PickupRateRequest() {
            this.alternateAddressIndicatorField = "N";
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://www.ups.com/XMLSchema/XOLTWS/Common/v1.0")]
        public RequestType Request {
            get {
                return this.requestField;
            }
            set {
                this.requestField = value;
            }
        }
        
        /// <remarks/>
        public AddressType PickupAddress {
            get {
                return this.pickupAddressField;
            }
            set {
                this.pickupAddressField = value;
            }
        }
        
        /// <remarks/>
        public string AlternateAddressIndicator {
            get {
                return this.alternateAddressIndicatorField;
            }
            set {
                this.alternateAddressIndicatorField = value;
            }
        }
        
        /// <remarks/>
        public string ServiceDateOption {
            get {
                return this.serviceDateOptionField;
            }
            set {
                this.serviceDateOptionField = value;
            }
        }
        
        /// <remarks/>
        public PickupDateInfoType PickupDateInfo {
            get {
                return this.pickupDateInfoField;
            }
            set {
                this.pickupDateInfoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.ups.com/XMLSchema/XOLTWS/Pickup/v1.1")]
    public partial class PickupRateResponse {
        
        private ResponseType responseField;
        
        private RateResultType rateResultField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://www.ups.com/XMLSchema/XOLTWS/Common/v1.0")]
        public ResponseType Response {
            get {
                return this.responseField;
            }
            set {
                this.responseField = value;
            }
        }
        
        /// <remarks/>
        public RateResultType RateResult {
            get {
                return this.rateResultField;
            }
            set {
                this.rateResultField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.ups.com/XMLSchema/XOLTWS/Pickup/v1.1")]
    public partial class PickupCancelRequest {
        
        private RequestType requestField;
        
        private string cancelByField;
        
        private string pRNField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://www.ups.com/XMLSchema/XOLTWS/Common/v1.0")]
        public RequestType Request {
            get {
                return this.requestField;
            }
            set {
                this.requestField = value;
            }
        }
        
        /// <remarks/>
        public string CancelBy {
            get {
                return this.cancelByField;
            }
            set {
                this.cancelByField = value;
            }
        }
        
        /// <remarks/>
        public string PRN {
            get {
                return this.pRNField;
            }
            set {
                this.pRNField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.ups.com/XMLSchema/XOLTWS/Pickup/v1.1")]
    public partial class PickupCancelResponse {
        
        private ResponseType responseField;
        
        private string pickupTypeField;
        
        private StatusCodeDescriptionType gWNStatusField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://www.ups.com/XMLSchema/XOLTWS/Common/v1.0")]
        public ResponseType Response {
            get {
                return this.responseField;
            }
            set {
                this.responseField = value;
            }
        }
        
        /// <remarks/>
        public string PickupType {
            get {
                return this.pickupTypeField;
            }
            set {
                this.pickupTypeField = value;
            }
        }
        
        /// <remarks/>
        public StatusCodeDescriptionType GWNStatus {
            get {
                return this.gWNStatusField;
            }
            set {
                this.gWNStatusField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.ups.com/XMLSchema/XOLTWS/Pickup/v1.1")]
    public partial class PickupPendingStatusRequest {
        
        private RequestType requestField;
        
        private string pickupTypeField;
        
        private string accountNumberField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://www.ups.com/XMLSchema/XOLTWS/Common/v1.0")]
        public RequestType Request {
            get {
                return this.requestField;
            }
            set {
                this.requestField = value;
            }
        }
        
        /// <remarks/>
        public string PickupType {
            get {
                return this.pickupTypeField;
            }
            set {
                this.pickupTypeField = value;
            }
        }
        
        /// <remarks/>
        public string AccountNumber {
            get {
                return this.accountNumberField;
            }
            set {
                this.accountNumberField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.ups.com/XMLSchema/XOLTWS/Pickup/v1.1")]
    public partial class PickupPendingStatusResponse {
        
        private ResponseType responseField;
        
        private PendingStatusType[] pendingStatusField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://www.ups.com/XMLSchema/XOLTWS/Common/v1.0")]
        public ResponseType Response {
            get {
                return this.responseField;
            }
            set {
                this.responseField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("PendingStatus")]
        public PendingStatusType[] PendingStatus {
            get {
                return this.pendingStatusField;
            }
            set {
                this.pendingStatusField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void ProcessPickupCreationCompletedEventHandler(object sender, ProcessPickupCreationCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ProcessPickupCreationCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ProcessPickupCreationCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public PickupCreationResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((PickupCreationResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void ProcessPickupRateCompletedEventHandler(object sender, ProcessPickupRateCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ProcessPickupRateCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ProcessPickupRateCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public PickupRateResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((PickupRateResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void ProcessPickupCancelCompletedEventHandler(object sender, ProcessPickupCancelCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ProcessPickupCancelCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ProcessPickupCancelCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public PickupCancelResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((PickupCancelResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void ProcessPickupPendingStatusCompletedEventHandler(object sender, ProcessPickupPendingStatusCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ProcessPickupPendingStatusCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ProcessPickupPendingStatusCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public PickupPendingStatusResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((PickupPendingStatusResponse)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591