//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.18444.
// 
#pragma warning disable 1591

namespace ABCLogisticsCloudDatabaseApp.ABCLogisticsGlobalGeoWebServiceReference {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="GeoWebServiceSoap", Namespace="http://www.sbaglobal.com")]
    public partial class GeoWebService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback GeocodeAddressOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetRouteDistanceOperationCompleted;
        
        private System.Threading.SendOrPostCallback GeocodeZipCodeOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public GeoWebService() {
            this.Url = global::ABCLogisticsCloudDatabaseApp.Properties.Settings.Default.ABCLogisticsCloudDatabaseApp_ABCLogisticsGlobalGeoWebServiceReference_GeoWebService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event GeocodeAddressCompletedEventHandler GeocodeAddressCompleted;
        
        /// <remarks/>
        public event GetRouteDistanceCompletedEventHandler GetRouteDistanceCompleted;
        
        /// <remarks/>
        public event GeocodeZipCodeCompletedEventHandler GeocodeZipCodeCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.sbaglobal.com/GeocodeAddress", RequestNamespace="http://www.sbaglobal.com", ResponseNamespace="http://www.sbaglobal.com", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public GeoLocation GeocodeAddress(string address, string city, string state, string zipcode) {
            object[] results = this.Invoke("GeocodeAddress", new object[] {
                        address,
                        city,
                        state,
                        zipcode});
            return ((GeoLocation)(results[0]));
        }
        
        /// <remarks/>
        public void GeocodeAddressAsync(string address, string city, string state, string zipcode) {
            this.GeocodeAddressAsync(address, city, state, zipcode, null);
        }
        
        /// <remarks/>
        public void GeocodeAddressAsync(string address, string city, string state, string zipcode, object userState) {
            if ((this.GeocodeAddressOperationCompleted == null)) {
                this.GeocodeAddressOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGeocodeAddressOperationCompleted);
            }
            this.InvokeAsync("GeocodeAddress", new object[] {
                        address,
                        city,
                        state,
                        zipcode}, this.GeocodeAddressOperationCompleted, userState);
        }
        
        private void OnGeocodeAddressOperationCompleted(object arg) {
            if ((this.GeocodeAddressCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GeocodeAddressCompleted(this, new GeocodeAddressCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.sbaglobal.com/GetRouteDistance", RequestNamespace="http://www.sbaglobal.com", ResponseNamespace="http://www.sbaglobal.com", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public double GetRouteDistance(GeoLocation fromAddress, GeoLocation toAddress) {
            object[] results = this.Invoke("GetRouteDistance", new object[] {
                        fromAddress,
                        toAddress});
            return ((double)(results[0]));
        }
        
        /// <remarks/>
        public void GetRouteDistanceAsync(GeoLocation fromAddress, GeoLocation toAddress) {
            this.GetRouteDistanceAsync(fromAddress, toAddress, null);
        }
        
        /// <remarks/>
        public void GetRouteDistanceAsync(GeoLocation fromAddress, GeoLocation toAddress, object userState) {
            if ((this.GetRouteDistanceOperationCompleted == null)) {
                this.GetRouteDistanceOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetRouteDistanceOperationCompleted);
            }
            this.InvokeAsync("GetRouteDistance", new object[] {
                        fromAddress,
                        toAddress}, this.GetRouteDistanceOperationCompleted, userState);
        }
        
        private void OnGetRouteDistanceOperationCompleted(object arg) {
            if ((this.GetRouteDistanceCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetRouteDistanceCompleted(this, new GetRouteDistanceCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.sbaglobal.com/GeocodeZipCode", RequestNamespace="http://www.sbaglobal.com", ResponseNamespace="http://www.sbaglobal.com", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public GeoLocation GeocodeZipCode(string zipcode) {
            object[] results = this.Invoke("GeocodeZipCode", new object[] {
                        zipcode});
            return ((GeoLocation)(results[0]));
        }
        
        /// <remarks/>
        public void GeocodeZipCodeAsync(string zipcode) {
            this.GeocodeZipCodeAsync(zipcode, null);
        }
        
        /// <remarks/>
        public void GeocodeZipCodeAsync(string zipcode, object userState) {
            if ((this.GeocodeZipCodeOperationCompleted == null)) {
                this.GeocodeZipCodeOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGeocodeZipCodeOperationCompleted);
            }
            this.InvokeAsync("GeocodeZipCode", new object[] {
                        zipcode}, this.GeocodeZipCodeOperationCompleted, userState);
        }
        
        private void OnGeocodeZipCodeOperationCompleted(object arg) {
            if ((this.GeocodeZipCodeCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GeocodeZipCodeCompleted(this, new GeocodeZipCodeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.sbaglobal.com")]
    public partial class GeoLocation {
        
        private double latitudeField;
        
        private double longitudeField;
        
        /// <remarks/>
        public double Latitude {
            get {
                return this.latitudeField;
            }
            set {
                this.latitudeField = value;
            }
        }
        
        /// <remarks/>
        public double Longitude {
            get {
                return this.longitudeField;
            }
            set {
                this.longitudeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void GeocodeAddressCompletedEventHandler(object sender, GeocodeAddressCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GeocodeAddressCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GeocodeAddressCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public GeoLocation Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((GeoLocation)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void GetRouteDistanceCompletedEventHandler(object sender, GetRouteDistanceCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetRouteDistanceCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetRouteDistanceCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public double Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((double)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void GeocodeZipCodeCompletedEventHandler(object sender, GeocodeZipCodeCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GeocodeZipCodeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GeocodeZipCodeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public GeoLocation Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((GeoLocation)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591