//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ABCLogisticsCloudDatabaseApp.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.5.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=localhost;Initial Catalog=FFM;Persist Security Info=True;User ID=ABCL" +
            "ogisticsWebsite;Password=pwd")]
        public string FFMConnectionString {
            get {
                return ((string)(this["FFMConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=localhost;Initial Catalog=ABCLogistics_Global;Persist Security Info=T" +
            "rue;User ID=ABCLogisticsWebsite;Password=pwd")]
        public string ABCLogistics_GlobalConnectionString {
            get {
                return ((string)(this["ABCLogistics_GlobalConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://www.abclogistics.com/abclogisticswebservices/geowebservice.asmx")]
        public string ABCLogisticsCloudDatabaseApp_ABCLogisticsGlobalGeoWebServiceReference_GeoWebService {
            get {
                return ((string)(this["ABCLogisticsCloudDatabaseApp_ABCLogisticsGlobalGeoWebServiceReference_GeoWebServi" +
                    "ce"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost/ABCLogisticsGlobalshipment/ABCLogistics_GlobalShipment.asmx")]
        public string ABCLogisticsCloudDatabaseApp_ABCLogisticsDevFFMShipmentWebReference_ABCLogistics_GlobalShipment {
            get {
                return ((string)(this["ABCLogisticsCloudDatabaseApp_ABCLogisticsDevFFMShipmentWebReference_ABCLogistics_" +
                    "GlobalShipment"]));
            }
        }
    }
}
