//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
namespace CarrierDevApp.Entity
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class CarrierDatabaseEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new CarrierDatabaseEntities object using the connection string found in the 'CarrierDatabaseEntities' section of the application configuration file.
        /// </summary>
        public CarrierDatabaseEntities() : base("name=CarrierDatabaseEntities", "CarrierDatabaseEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new CarrierDatabaseEntities object.
        /// </summary>
        public CarrierDatabaseEntities(string connectionString) : base(connectionString, "CarrierDatabaseEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new CarrierDatabaseEntities object.
        /// </summary>
        public CarrierDatabaseEntities(EntityConnection connection) : base(connection, "CarrierDatabaseEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<BookingCountry> BookingCountries
        {
            get
            {
                if ((_BookingCountries == null))
                {
                    _BookingCountries = base.CreateObjectSet<BookingCountry>("BookingCountries");
                }
                return _BookingCountries;
            }
        }
        private ObjectSet<BookingCountry> _BookingCountries;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the BookingCountries EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToBookingCountries(BookingCountry bookingCountry)
        {
            base.AddObject("BookingCountries", bookingCountry);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="CarrierDatabaseModel", Name="BookingCountry")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class BookingCountry : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new BookingCountry object.
        /// </summary>
        /// <param name="countryID">Initial value of the CountryID property.</param>
        public static BookingCountry CreateBookingCountry(global::System.Int32 countryID)
        {
            BookingCountry bookingCountry = new BookingCountry();
            bookingCountry.CountryID = countryID;
            return bookingCountry;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 CountryID
        {
            get
            {
                return _CountryID;
            }
            set
            {
                if (_CountryID != value)
                {
                    OnCountryIDChanging(value);
                    ReportPropertyChanging("CountryID");
                    _CountryID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("CountryID");
                    OnCountryIDChanged();
                }
            }
        }
        private global::System.Int32 _CountryID;
        partial void OnCountryIDChanging(global::System.Int32 value);
        partial void OnCountryIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String CountryName
        {
            get
            {
                return _CountryName;
            }
            set
            {
                OnCountryNameChanging(value);
                ReportPropertyChanging("CountryName");
                _CountryName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("CountryName");
                OnCountryNameChanged();
            }
        }
        private global::System.String _CountryName;
        partial void OnCountryNameChanging(global::System.String value);
        partial void OnCountryNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Alpha2Code
        {
            get
            {
                return _Alpha2Code;
            }
            set
            {
                OnAlpha2CodeChanging(value);
                ReportPropertyChanging("Alpha2Code");
                _Alpha2Code = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Alpha2Code");
                OnAlpha2CodeChanged();
            }
        }
        private global::System.String _Alpha2Code;
        partial void OnAlpha2CodeChanging(global::System.String value);
        partial void OnAlpha2CodeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Alpha3Code
        {
            get
            {
                return _Alpha3Code;
            }
            set
            {
                OnAlpha3CodeChanging(value);
                ReportPropertyChanging("Alpha3Code");
                _Alpha3Code = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Alpha3Code");
                OnAlpha3CodeChanged();
            }
        }
        private global::System.String _Alpha3Code;
        partial void OnAlpha3CodeChanging(global::System.String value);
        partial void OnAlpha3CodeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String DHLPickupRegion
        {
            get
            {
                return _DHLPickupRegion;
            }
            set
            {
                OnDHLPickupRegionChanging(value);
                ReportPropertyChanging("DHLPickupRegion");
                _DHLPickupRegion = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("DHLPickupRegion");
                OnDHLPickupRegionChanged();
            }
        }
        private global::System.String _DHLPickupRegion;
        partial void OnDHLPickupRegionChanging(global::System.String value);
        partial void OnDHLPickupRegionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Zone
        {
            get
            {
                return _Zone;
            }
            set
            {
                OnZoneChanging(value);
                ReportPropertyChanging("Zone");
                _Zone = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Zone");
                OnZoneChanged();
            }
        }
        private global::System.String _Zone;
        partial void OnZoneChanging(global::System.String value);
        partial void OnZoneChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String DHLRateRegion
        {
            get
            {
                return _DHLRateRegion;
            }
            set
            {
                OnDHLRateRegionChanging(value);
                ReportPropertyChanging("DHLRateRegion");
                _DHLRateRegion = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("DHLRateRegion");
                OnDHLRateRegionChanged();
            }
        }
        private global::System.String _DHLRateRegion;
        partial void OnDHLRateRegionChanging(global::System.String value);
        partial void OnDHLRateRegionChanged();

        #endregion

    
    }

    #endregion

    
}
